import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'

import { Toaster } from 'react-hot-toast'

import NavbarComponent from '@/app/components/Navbar'
import Container from '@/app/components/Container'
import FooterComponent from '@/app/components/Footer'

import { UserProvider } from '@/app/context/UserContex'
import { StoresProvider } from '@/app/context/StoresContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <UserProvider>
                    <StoresProvider>
                        <Container>
                            <NavbarComponent />
                            {children}
                            <FooterComponent />

                            <Toaster />
                        </Container>
                    </StoresProvider>
                </UserProvider>
            </body>
        </html>
    )
}
